### ISSUE TITLE
Mocking Union types

### ISSUE THREAD

**Issue by diegonc** [apollostack/apollo-starter-kit#9] opened 2016-05-23 22:19 UTC
Hello

I'm about to start writing a GraphQL server using apollo so I decided to follow the "idea" behind the tutorial but adding my own types.

So I added the User type:
```
type User {
   id: ID!
   credentials: EmailAccount
}
```
and the EmailAccount where the email and password are stored:
```
type EmailAccount {
  email: String!
  password: String!
}
```
Then I added the `aUser: User` field to the Query type and everything worked just fine (that is getting "It works!" strings all over the place :)

The next step would be to add another kind of account, say GitHub:
```
type EmailAccount {
  typename: String!
  email: String!
  password: String!
}

type GitHubAccount {
  typename: String!
  handle: String
  token: String!  # or whatever is relevant used to authenticate the user, I'm not there yet
}

# Now we have two accounts
union Credentials = EmailAccount | GitHubAccount

# And the user could be relying on any of them
type User {
   id: ID!
   credentials: Credentials
}
```
Unfortunately when querying the aUser I get the error message:
> "Could not determine runtime type of value \"[object Object]\" for field User.credentials."
and `null` is returned in the data's credentials field.

According to [this issue](https://github.com/apollostack/graphql-tools/issues/34), for mocking to work a resolveType function for the union type should be specified. So I tried the following resolver (copying from the testcases commited in the referenced pull request)
```
const resolveFunctions = {
	Credentials: {
		__resolveType(data, ctx, info) {
			return info.schema.getType(data.typename);
		}
	}
};
```
and called apolloServer like below:
```
graphQLServer.use('/', apolloServer({
  graphiql: true,
  pretty: true,
  schema: Schema,
  resolvers: resolveFunctions,
  mocks: Mocks,
}));
```
but it did not work (same error message).

I'd like to have a more complete schema before proceeding to implement resolvers; and default mocking was working just fine for that purpose.

**Is there any way to attach just the resolveType function to union types without disabling mocking?**

Thanks!

--

This is more a question than an issue report, I know, but I couldn't find a better place to post it :(

**Comment by helfer** [comment] 2016-05-24 01:03
I think it should work even when you don't implement __resolveType for
unions. Can you show me the query that you're trying to run or - even
better - point me to a repo with a reproduction?

**Comment by helfer** [comment] 2016-05-24 01:08
Also, what does your Mocks object look like?

**Comment by diegonc** [comment] 2016-05-24 03:01
I uploaded the reproduction to my github account:

- repo: https://github.com/diegonc/apollo-starter-kit
- changes: https://github.com/apollostack/apollo-starter-kit/compare/server-only...diegonc:tc/issue-9?expand=1

To test it I used the following query
```
{
  aUser {
    id
    credentials {
      ... on EmailAccount {
        typename
        email
      }
      ... on GitHubAccount {
        typename
        token
      }
    }
  }
}
```
The mock object is the one provided by the starter kit:
```
const mocks = {
  String: () => 'It works!'
};

export default mocks;
```

**Comment by helfer** [comment] 2016-05-24 09:58
Ok, this is a bug in apolloServer. If mocks are provided, the resolvers argument (which is necessary in this case, even though I initially thought otherwise) is not used at all. Could you open an issue on graphql-tools  about this so I don't forget to fix it? Or if you want, you could try making a PR for graphql-tools to make sure resolveFunctions are used even when mocks are defined.

For the time being, you could use the following workaround:

```
import { makeExecutableSchema, addMockFunctionsToSchema, apolloServer } from 'graphql-tools';

// ...

const schema = makeExecutableSchema({ typeDefs: Schema, resolvers: Resolvers });
addMockFunctionsToSchema({ schema, mocks: Mocks });
app.use('/graphql', apolloServer({ schema, graphiql: true }));
```

**Comment by helfer** [comment] 2016-05-24 13:35
If you are willing to make a PR to fix it, but aren't sure how, I could tell you exactly what to do where 😀 

Otherwise, I will probably get around to doing it in a few days. Either way, let me know!

**Comment by diegonc** [comment] 2016-05-24 14:04
> El 24 may 2016, a las 10:35, Jonas Helfer <notifications@github.com> escribió:
> If you are willing to make a PR to fix it, but aren't sure how, I could tell you exactly what to do where 😀
> 
I think I found what to do. I'll add a call to addResolveFunctionsToSchema in the middleware apolloServer returns; under the "if mocks" true branch.

Now I'm figuring how to test it. I may need to do some tweaks in the schema  at test/testApolloServer.js
> Otherwise, I will probably get around to doing it in a few days. Either way, let me know!
> 
Sorry, it was getting late yesterday. I saw the more recent responses this morning.

I just posted an issue against graphql-tools. It looks easy so I'll attempt to make a pull request for you to review.

**Comment by helfer** [comment] 2016-05-24 23:42
I just published a new version of graphql-tools with your PR, and this issue should be fixed if you update graphql-tools to 0.4.2. Can you confirm that and make a PR here to update the dependency?

Thanks!

**Comment by diegonc** [comment] 2016-05-25 02:48
Yes it works, thanks!. The PR is against master; do the other branches need PRs?

**Comment by stubailo** [comment] 2016-05-25 02:54
Looks like this is fixed!

**Comment by stubailo** [comment] 2016-05-25 02:54
I think master is the only important branch, but @helfer can reopen if not.

**Comment by helfer** [comment] 2016-05-25 03:02
Yeah, would be great if we could have this on the other two branches as well!

**Comment by diegonc** [comment] 2016-05-29 18:13
Hi @helfer, I just made two new PRs to update the remaining branches.
I wasn't sure if merging master into them was safe to do, so I cherry picked the commit from master.

**Comment by helfer** [comment] 2016-05-29 20:01
@diegonc Thanks a lot!

Since we don't have any CI tests set up for the starter kit, I'll have to clone the repo and make sure it still works before I merge the PRs. I'll do that when I get back to work on Tuesday.

**Closed** 2016-06-05 23:11 UTC
